# Generated by Django 4.2 on 2024-07-17 01:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('agreement_id', models.IntegerField(null=True)),
                ('agreementType', models.CharField(max_length=300, null=True)),
                ('first_party_address', models.CharField(max_length=100)),
                ('first_party_name', models.CharField(max_length=200)),
                ('first_party_valid_id', models.CharField(max_length=64, null=True)),
                ('first_party_country', models.CharField(max_length=300, null=True)),
                ('first_party_id_type', models.CharField(max_length=300, null=True)),
                ('first_party_signature', models.FileField(blank=True, null=True, upload_to='signatures/')),
                ('second_party_address', models.CharField(max_length=100)),
                ('second_party_name', models.CharField(max_length=200)),
                ('second_party_valid_id', models.CharField(max_length=64, null=True)),
                ('second_party_country', models.CharField(max_length=300, null=True)),
                ('second_party_id_type', models.CharField(max_length=300, null=True)),
                ('second_party_signature', models.FileField(blank=True, null=True, upload_to='signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
