# Generated by Django 5.0.6 on 2024-06-25 18:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_party_address', models.CharField(max_length=100)),
                ('first_party_name', models.CharField(max_length=200)),
                ('first_party_valid_id', models.CharField(max_length=64)),
                ('first_party_signature', models.FileField(blank=True, null=True, upload_to='signatures/')),
                ('second_party_address', models.CharField(max_length=100)),
                ('second_party_name', models.CharField(max_length=200)),
                ('second_party_valid_id', models.CharField(max_length=64)),
                ('second_party_signature', models.FileField(blank=True, null=True, upload_to='signatures/')),
            ],
        ),
    ]
