# Generated by Django 4.2 on 2024-07-17 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalagreement',
            name='first_party_name',
        ),
        migrations.RemoveField(
            model_name='legalagreement',
            name='second_party_name',
        ),
    ]
